### ISSUE TITLE
Regression, unable to override String color with lush

### ISSUE THREAD

**Issue by cmlaverdiere** [mcchrish/zenbones.nvim#107]
I've had the following config for a year to highlight strings as blue, but it's stopped working recently without any changes other than updating the plugin.

```
local lush = require "lush"
local base = require "zenbones"
local water = lush.hsluv(236, 64, 61)

-- Create some specs
local specs = lush.parse(function()
	return {
		String { base.String, fg = water },
	}
end)

-- Apply specs using lush tool-chain
lush.apply(lush.compile(specs))
```

The highlight works if I replace `String` with `Comment`, but something specific to String has stopped working.

**Comment by mcchrish** [comment]
It might be linked to the update to nvim-treesitter. There is no default links anymore, so we had to define them in this repo. https://github.com/rktjmp/lush.nvim/issues/109
We link treesitter `@string` to `Constant`. Can you try to override that instead?

**Comment by cmlaverdiere** [comment]
Overriding Constant seems to work well enough, thanks!
