### ISSUE TITLE
ask about float background

### ISSUE THREAD

**Issue by phdhary** [mcchrish/zenbones.nvim#108]
Hi thanks for this colorschemes.

I'm very used to having bordered floating window (like the one in hover).

![lsp-hover](https://user-images.githubusercontent.com/56226582/218088988-e193a6d1-7ca9-4f07-aa01-2caf85e3f3a5.png)

Is it possible to set the floating background to be the same as the regular one behind it?

**Comment by phdhary** [comment]
nevermind, I'm able to solve it after some digging.

maybe this snippets help others. (I also disable the 'italic everywhere' things with this)
```lua
vim.api.nvim_create_autocmd("ColorScheme", {
	group = "YourGroupName",
	callback = function()
		local colors = vim.g.colors_name
		if colors:match ".*bones" or colors == "zenwritten" or colors == "zenburned" then
			vim.cmd [[
                    highlight! Number gui=NONE   " disable italic
                    highlight! Constant gui=NONE " disable italic
                    highlight! String gui=NONE   " disable italic
                    highlight! link NormalFloat Normal " set floating bg to regular bg
                    ]]
		end
	end,
	desc = "Some zenbones autocmd",
})
```

**Comment by pernambucano** [comment]
If you're reading this, and what to use the autocmd, make sure to put it after you call set your colorscheme.

For example, in my config I do this:

```lua
      vim.cmd.colorscheme("zenbones")

      vim.api.nvim_create_autocmd("ColorScheme", {
        pattern = "zenbones",
        callback = function()
          vim.api.nvim_set_hl(0, 'NormalFloat', { link = "Normal" })
        end,
        desc = "Override Zenbones",
      })
```
