### ISSUE TITLE
Statuscolumn highlighting removed on lines with diagnostics

### ISSUE THREAD

**Issue by gegoune** [mcchrish/zenbones.nvim#111]
Hey,

with
```lua
vim.g.zenwritten = {
  solid_line_nr = true,
}

vim.cmd.colorscheme 'zenwritten'
```
background (`solid_line_nr`) is removed from lines containing diagnostics:

<img width="56" alt="diags" src="https://user-images.githubusercontent.com/69750637/224412538-c491dfab-6a16-472b-895c-741e88aec72d.png">

I think it would look better/more consistent if diagnostic lines also had background on linenr.

(Great colorschemes! Thanks!)

**Comment by mcchrish** [comment]
Thanks for reporting. Can you share your config related to the statuscolumn?

**Comment by gegoune** [comment]
```lua
vim.opt.statuscolumn = ' %C%=%l%s%#Normal# '
```
Sign used for diagnostic, one on screenshot is `' 🮇'` (https://www.compart.com/en/unicode/U+2595).

**Comment by gegoune** [comment]
It was actually down to highlight group I was setting up for my signs, completely forgot about it, apologies for the noise.
