### ISSUE TITLE
Questions about nvim-cmp

### ISSUE THREAD

**Issue by windowsrefund** [mcchrish/zenbones.nvim#119]
Hello. Thanks for these themes. I'm using zenbones and have a few questions.
![Screenshot_2023-05-20_10-42-41](https://github.com/mcchrish/zenbones.nvim/assets/512222/4b34a536-339f-48fd-81a2-91c4f9c123fe)

1. As seen in the image, the autocomplete list provided by nvim-cmp is showing the selected item (yes, the first item really is selected) using a darker highlight. It's terribly difficult to distinguish and I'm wondering how I could change that the background to any of the zenbones native colors (blue, green, pink, etc)?

2. Why are the background colors so different between the autocomplete list and the documentation window?

Thanks in advance for any assistance.

**Comment by mcchrish** [comment]
Hey, do you have a specific config for cmp? On mine it looks alright:
<img width="1000" alt="image" src="https://github.com/mcchrish/zenbones.nvim/assets/7200153/8a51a3e9-a6c7-4c8d-853e-a3ec88701c2f">
