### ISSUE TITLE
Incorrect highlight for Noice's command/search floating window

### ISSUE THREAD

**Issue by gegoune** [mcchrish/zenbones.nvim#124]
Hey, I have noticed that there is highlighting issue with border and caret  of Noice's cmd window when `solid_line_nr` is set to `true`:

<img width="555" alt="noice" src="https://github.com/mcchrish/zenbones.nvim/assets/69750637/6494ec8c-7c12-4107-beef-0058295054d7">

With it set to `false` you get expected result:

<img width="545" alt="bones" src="https://github.com/mcchrish/zenbones.nvim/assets/69750637/a67ea9c8-ac82-416f-ac3e-323c10edf8cd">

**Comment by mcchrish** [comment]
I just pushed some highlighting groups for noice.
By default they are linked to DiagnosticSignInfo where it gets the background color from.

**Comment by gegoune** [comment]
Looks very good, thank you! Closing.
