### ISSUE TITLE
Submit to kitty-themes?

### ISSUE THREAD

**Issue by stefanvanburen** [mcchrish/zenbones.nvim#144]
https://github.com/kovidgoyal/kitty-themes

I think this would be similar to https://github.com/kovidgoyal/kitty-themes/pull/97/files where it's mostly adding links to the upstream files and making them conform to the template. Happy to do it myself if you're fine with it.

**Comment by mcchrish** [comment]
Isn't it there already? https://github.com/search?q=repo%3Akovidgoyal%2Fkitty-themes%20zenbones&type=code

**Comment by stefanvanburen** [comment]
ah, you're right - no idea how I missed that, sorry!
