### ISSUE TITLE
Support changed treesitter highlight groups neovim 0.10

### ISSUE THREAD

**Issue by jryom** [mcchrish/zenbones.nvim#175]
Neovim 0.10 changes treesitter highlight groups, which breaks highlighting a lot of ways.

https://neovim.io/doc/user/news-0.10.html#_-breaking-changes

https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0

https://neovim.io/doc/user/treesitter.html#treesitter-highlight-groups

**Comment by mcchrish** [comment]
This is already supported here https://github.com/mcchrish/zenbones.nvim/blob/453ec69d82d644ee6998a3464da49d0261df9f80/lua/zenbones/specs/dark.lua#L193-L312, correct?

**Comment by jryom** [comment]
Hmm, not sure. I accidentally upgraded neovim on my personal machine yesterday and just noticed that some of the highlights look pretty broken:

<img width="633" alt="Screenshot 2024-05-17 at 09 41 58" src="https://github.com/mcchrish/zenbones.nvim/assets/2834949/d0b600ea-de6c-44b6-b034-a505503dc289">

I haven't dug more into it, so it might only be one highlight group that needs some adjustments.

**Comment by mcchrish** [comment]
Hmm, those looks like the colors from the new default neovim colorscheme. At least for the strings.

Seems like if you remove the `vim.g.zenbones_compat = 1` it works.

**Comment by jryom** [comment]
Thanks for the workaround, it does indeed fix the issue. Reason I ran in compat mode was to avoid having to install the additional dependency, since I don't really care about customizing the theme.

**Comment by zakj** [comment]
I don't think this is entirely fixed; I can reproduce with a string in a Python file:

<img width="841" alt="Screenshot 2024-05-18 at 11 05 32 AM" src="https://github.com/mcchrish/zenbones.nvim/assets/24062/77888e9c-1bd6-4902-958b-762e7c01ec6d">

Looks like zenbones doesn't override the default `String` highlight:

https://github.com/mcchrish/zenbones.nvim/blob/453ec69d82d644ee6998a3464da49d0261df9f80/lua/zenbones/specs/dark.lua#L118
