### ISSUE TITLE
Experimental neovim website theme

### ISSUE THREAD

**Issue by mcchrish** [mcchrish/zenbones.nvim#3]
<img width="1187" alt="Screen Shot 2021-08-26 at 5 30 44 PM" src="https://user-images.githubusercontent.com/7200153/130938906-6cab9b3c-59d5-48b3-96ee-fa34acfca8b2.png">

<img width="1128" alt="Screen Shot 2021-08-26 at 6 13 02 PM" src="https://user-images.githubusercontent.com/7200153/130945270-81cac5a4-5303-4e75-bc1a-6379e182ebf5.png">

Works by just changing:

https://github.com/mcchrish/zenbones.nvim/blob/666881476681953604851f01d773316191f91e5a/lua/zenbones/colors.lua#L5-L6

To:

```lua
	sand = hsluv("#e7eee8"),
	stone = hsluv("#202e18"),
```

**Comment by connorlay** [comment]
This is really cool! I've been looking for a mostly-monochrome NeoVim color scheme. Do you happen to have an example of configuring this via Lush?

**Comment by mcchrish** [comment]
@connorlay sorry of the late response. I'm just finishing the zenflesh version.

Check this out.

Light:
<img width="1128" alt="Screen Shot 2021-09-17 at 8 06 28 PM" src="https://user-images.githubusercontent.com/7200153/133780431-938bad2f-7100-4086-8959-06b211ab73d1.png">

Dark:
<img width="1128" alt="Screen Shot 2021-09-17 at 8 06 40 PM" src="https://user-images.githubusercontent.com/7200153/133780477-3303f097-388e-4ad6-b3b6-9e3c9117dca7.png">

I just copied the fg and bg colors of the neovim site:
<img width="233" alt="Screen Shot 2021-09-17 at 8 07 15 PM" src="https://user-images.githubusercontent.com/7200153/133780616-b11e0da7-9160-4da0-a883-90cf823849a2.png">

Here's the branch if you want to check out further. https://github.com/mcchrish/zenbones.nvim/tree/neovim-io

Honestly, I'm thinking of opening up an API where users can tweak the palette to their likings.

**Comment by connorlay** [comment]
> Honestly, I'm thinking of opening up an API where users can tweak the palette to their likings.

That's a great idea! I played around with Lush a bit but I'm not sure if you can change the initial color definitions via extensions or not. Those screenshots look great by the way 💯

**Comment by mcchrish** [comment]
Neovim colors is officially in this repo. https://github.com/mcchrish/zenbones.nvim/blob/main/colors/neovim.lua

It is set as an example of how to extend zenbones colors and make a personal theme out of it.
