### ISSUE TITLE
Since the recent update the theme is glitching when neovim starts

### ISSUE THREAD

**Issue by synaptiko** [mcchrish/zenbones.nvim#38]
Hey, I just updated zenbones and I've noticed that when neovim starts.

I can see the dark variant of the theme for a short time. It's much more visible when I open previously saved session with some bigger files (which probably causes neovim to do more work while initializing the plugins).

I'm using zplug with the following basic setup:
```
...
Plug 'mcchrish/zenbones.nvim'
Plug 'rktjmp/lush.nvim'
...

let g:zenbones_solid_vert_split=v:true
let g:zenbones_dim_noncurrent_window=v:false
colorscheme zenbones
```

**Comment by mcchrish** [comment]
What terminal are you using? I noticed the same behavior when I upgrade to iterm 3.4.12.
My observation is that it neovim base the background color on the terminal environment. https://github.com/neovim/neovim/pull/9509

If you set `set background=light`, you won't see the flash anymore.

**Comment by synaptiko** [comment]
I'm using Alacritty but it wasn't happening previously or in any other theme. Anyway, your advice with `background` helped, thank you.
