### ISSUE TITLE
Feature Request: darker status line variants

### ISSUE THREAD

**Issue by oblitum** [mcchrish/zenbones.nvim#57]
Hi. I really like this colorscheme, except for one caveat, all lualine (etc.) variants of dark colorschemes are too bright, specially when picking the stark flavor. They're nice as-is too, but I also wished for darker variants that would blend a bit better with dark background, specially stark ones. Maybe it's a good idea to tone it down when using stark?

![img-2021-11-14-185210](https://user-images.githubusercontent.com/1269815/141700041-508dc434-1ee8-4e63-9a5a-12a63193cda4.png)

**Comment by mcchrish** [comment]
I'll probably create a separate theme files for each like: `neobones_dark`, `neobones_dark_stark` `neobones_dark_warm`. While [themes/neobones.lua](https://github.com/mcchrish/zenbones.nvim/blob/1a020ee9c6972a3252109c7690bd042870c156e4/lua/lualine/themes/neobones.lua) will check the user `lightness`/`darkness` config and apply the matching theme.

I think this gives the most flexible option.
