### ISSUE TITLE
Feature: TreeSitter highlights

### ISSUE THREAD

**Issue by evantravers** [mcchrish/zenbones.nvim#58]
I have fallen hard for this color scheme… and really enjoy the flexibility, extras, and mindset.

I’m missing treesitter a touch. I’m going to give a stab at extending it or making a pull request, but I thought I’d throw it out there while I work on it.

**Comment by mcchrish** [comment]
Thanks for using this colorscheme!

I'm wondering what specific things are missing. I admit there are only few defined TS* specific links https://github.com/mcchrish/zenbones.nvim/blob/1a020ee9c6972a3252109c7690bd042870c156e4/lua/zenbones/specs/light.lua#L200-L250
but most are by default correctly mapped already.

Would love to see any additional improvements you can find.

There are also some new groups that needs to be added too. https://github.com/nvim-treesitter/nvim-treesitter/blob/89fbb9b39e9ff4049c797397721d44facbd246df/plugin/nvim-treesitter.vim#L30-L96

**Comment by evantravers** [comment]
🤦 

You are right… part of the problem was that I had updated a few things and broken TreeSitter. Very cool!

Maybe the only pull request I'll make is mentioning that the themes support TS in the README.md. :P
