### ISSUE TITLE
Support markdown treesitter groups

### ISSUE THREAD

**Issue by evantravers** [mcchrish/zenbones.nvim#63]
I'll try poking at this sometime soon and submit a PR… but according to the author's reddit post we need to implement highlights for:

- [x] `TSTitle`
- [x] `TSLiteral`
- [x] `TSEmphasis`
- [x] `TSStrong`
- [x] `TSURI`
- [x] `TSTextReference`
- [x] `TSPunctSpecial`
- [x] `TSStringEscape`

https://www.reddit.com/r/neovim/comments/rg97j4/treesitter_for_markdown/hoje1mg/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by mcchrish** [comment]
Sounds good. Looking forward to the PR.
