### ISSUE TITLE
[Terminal] tmux low contrast

### ISSUE THREAD

**Issue by thuanpham2311** [mcchrish/zenbones.nvim#7]
![image](https://user-images.githubusercontent.com/40050527/132153188-3b42a2bb-0eea-4c47-95c7-e40d079f2161.png)
![image](https://user-images.githubusercontent.com/40050527/132153210-391dc893-7181-4eaa-a09d-491e7367eca4.png)

Terminal: kitty, alacritty.

**Comment by mcchrish** [comment]
You'll probably have to change your tmux config to the colors you want.

I'll probably create a zenbones tmux theme config just like alacritty/kitty using a template (e.g. [extras](https://github.com/mcchrish/zenbones.nvim/tree/main/extras)) if I get the chance. But PRs are always welcome if you want to take on it.
