### ISSUE TITLE
Forestbones not under extra/ folder for terminal colors

### ISSUE THREAD

**Issue by astrlux** [mcchrish/zenbones.nvim#75]
The `forestbones` [light] colorscheme is my preferred choice! However, I can't find it under `extras/`, which means I can make my terminal use the same colors.

If I find some time, I'll take a crack at writing one for `kitty`.

**Comment by mcchrish** [comment]
It's actually intentional since [everforest](https://github.com/sainnhe/everforest), the colorscheme that inspired forestbones, already have terminal colors config.
You can find them here: https://github.com/sainnhe/everforest/wiki
