### ISSUE TITLE
Add kitty themes to the kitty-theme repo

### ISSUE THREAD

**Issue by pard68** [mcchrish/zenbones.nvim#78]
The kitty terminal has a command to change the colors/theme. Any kitty colorscheme located in the kitty-theme repo will automatically be available via `kitty +kitten themes`. It'd be great if the kitty configs could be added to the repo so zenbones users on kitty can quickly and easily change themes and have it managed the way kitty prefers.

I could do this, but I'd wouldn't want to unless you were okay with it since it's your work and such.

https://github.com/kovidgoyal/kitty-themes

**Comment by mcchrish** [comment]
It's no problem. Please go ahead 👍

**Comment by pard68** [comment]
Thanks @mcchrish, I've created a PR! https://github.com/kovidgoyal/kitty-themes/pull/31

**Comment by pard68** [comment]
The PR has been merged. I'll go ahead and close this issue.
