### ISSUE TITLE
Questions on theming shell and terminal emulators

### ISSUE THREAD

**Issue by ajitid** [mcchrish/zenbones.nvim#80]
First of all — thanks for making zenbones. It might made to switch a minimal scheme.

I, for the world, can't understand why Fish needs a separate set of color variables and can't re-use the colors a terminal emulator (like Kitty) provides. You seem to have a good understanding of it. Could you give explanation of why we need separate color variables — one for the terminal and one another for the shell? And also, is there an easy way to generate colorscheme for Fish shell?

![image](https://user-images.githubusercontent.com/26769888/154800834-3ec943a9-0207-4c27-8d37-7e13b4bef7b1.png)
_A screenshot showing Fish config UI to choose a colorscheme_

**Comment by mcchrish** [comment]
I'm not using Fish shell, so I don't really have a complete answer to your questions. For generating a template, yes it's possible using [shipwright.nvim](https://github.com/rktjmp/shipwright.nvim). Checkout this part where the templates are located: https://github.com/mcchrish/zenbones.nvim/tree/main/lua/zenbones/shipwright

An example of a fish color configuration we can base on:
https://github.com/rebelot/kanagawa.nvim/blob/master/extras/kanagawa.fish
