### ISSUE TITLE
Use major.minor.patch semver tags?

### ISSUE THREAD

**Issue by rktjmp** [mcchrish/zenbones.nvim#81]
I noticed the version tags are a mixture of full semver `major.minor.patch` and just `major.minor` or `major`. Not sure if you're actually doing _"Semantic Versioning"_ or just "Versioning", but per the [semver spec](https://semver.org/#spec-item-2) you're supposed to include all 3 parts for it to be valid.

**Comment by mcchrish** [comment]
Thanks for bringing this up. I'm loosely following semver just to mark the changes. I haven't read the full specs to be honest, but I'll take note of that requirement on succeeding releases. Thanks again!
