### ISSUE TITLE
Why zenbones show font differences in my terminal?

### ISSUE THREAD

**Issue by AstroShen** [mcchrish/zenbones.nvim#82]
I use nerd font Hack which support bold, italic and both. But I dont see any font differences like the screenshot demo in the readme?
I really love the zenbones colors.

**Comment by mcchrish** [comment]
What terminal are you using? Can you share a screenshot, and your configuration?

**Comment by AstroShen** [comment]
> I use nerd font Hack which support bold, italic and both. But I dont see any font differences like the screenshot demo in the readme?

Sorry to bother u. I use WSL in windows terminal, which doesnt support bold font in release version. I fix this mattern when i update windows terminal to preview version.

And btw, it there a way to customize font style for variable&keywords&fucntion, etc. I dont find the API  zenbone exposes.

**Comment by mcchrish** [comment]
> And btw, it there a way to customize font style for variable&keywords&fucntion, etc. I dont find the API zenbone exposes.

You can override highlights like this: https://github.com/mcchrish/zenbones.nvim/blob/main/doc/zenbones.md#extendoverride-highlights
or create your own colorscheme with the modifications you like: https://github.com/mcchrish/zenbones.nvim/blob/main/doc/zenbones.md#create-your-own-colorscheme
