### ISSUE TITLE
iTerm2 colors black/white are swapped

### ISSUE THREAD

**Issue by brunoroque06** [mcchrish/zenbones.nvim#85]
Thanks for the amazing color scheme!

I believe the following colors, for `zenbones/light`, are swapped on iTerm2 color scheme (`extras/iterm/zenbones.itermcolors`):

ansi 0 (black) <=> ansi 7 (white)
ansi 8 (bright black) <=> ansi 15 (bright white)

I briefly looked at `lua/zenbones/shipwright/runners/iterm.lua`, and that looks okay. The `zenbones/dark` (`extras/iterm/zenbones_dark.itermcolors`) seems to be correct as well.

Some cli tools might not work as intended if one "fixes" the colors, but that is because they hardcode white/black where they should use background/foreground instead, no? Was that the reason why this was done in the first place? I actually have 2 examples of this: `lazygit` does not work as intended with the "fixed" colors, while `tig` works better with the "fixed" colors.

Again, thanks for the color scheme.

**Comment by mcchrish** [comment]
> Some cli tools might not work as intended if one "fixes" the colors, but that is because they hardcode white/black where they should use background/foreground instead, no? Was that the reason why this was done in the first place? I actually have 2 examples of this: `lazygit` does not work as intended with the "fixed" colors, while `tig` works better with the "fixed" colors.

This is the exact reason. 🥲 Unfortunately, most CLI I use does not consider white theme correctly. I'm fine changing it to be consistent.

**Comment by brunoroque06** [comment]
Ah got it. Yes, I understand. It is not obvious which one is the best option. I will keep using the version where white is white, at least for now. Thanks for the reply. I will close the issue.
