### ISSUE TITLE
Unable to disable `italic_comments`

### ISSUE THREAD

**Issue by Blake-LeBlanc** [mcchrish/zenbones.nvim#90]
Great set of colorschemes! I'm having trouble disabling `italic_comments` with the config options shown in the documentation. What am I doing wrong? I've tried both within the `vim.cmd` block and as `lua`.

Thank you!

### colorschemes.lua
```
vim.cmd [[
try
  set background=light
  ...
  colorscheme zenbones

catch /^Vim\%((\a\+)\)\=:E185/
  colorscheme default
  set background=dark
endtry

" let g:zenbones = {
"   italic_comments = v:false
" }

" let g:zenbones_italic_comments = v:false

]]

vim.g.zenbones = { italic_comments = false }

```

**Comment by mcchrish** [comment]
Try setting the config first before calling `colorscheme`.
```vim
let g:zenbones_italic_comments = v:false
colorscheme zenbones
```

**Comment by Blake-LeBlanc** [comment]
> Try setting the config first before calling `colorscheme`.
> 
> ```viml
> let g:zenbones_italic_comments = v:false
> colorscheme zenbones
> ```

Great, thank you @mcchrish !
