### ISSUE TITLE
Generate extras for rosebones

### ISSUE THREAD

**Issue by felipesere** [mcchrish/zenbones.nvim#93]
👋 I really like your light vim themes! 

Is there a chance we could get the alacritty and tmux files generated for rosebones and forestbones?
I can probably try to create PR tonight 🙂

**Comment by mcchrish** [comment]
Hello. They are not generate because rose-pine and everforest already provides themes for alacritty. For tmux, the theme usually is defined by user config, but maybe we could generate as well.
